### ISSUE TITLE
The future 

### ISSUE THREAD

**Issue by Tach-Yon** [TheeWiki/Elvarg#13]
Would we be potentially aiming towards creating a functional RSPS and gathering a player-base in the future?

**Comment by LeviticusRS** [comment]
The use of this github is to promote this base and keep it active to possibly becoming a widely used base and a replacement for PI.

**Comment by Tach-Yon** [comment]
Interesting, I would like to see this base start using more modern forum softwares and create a very smooth API with, for example: NodeBB

https://github.com/NodeBB/NodeBB

**Comment by TheeWiki** [comment]
The main concept of this github is for the general public rsps programmers to contribute contents to a single rsps that is efficient and a great learning experience for everyone. People can locally make personal changes for their future personal rsps.

Ideally as well the community contributes to creating a fully functional rsps to use with ease.
